name: Benchmark

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:

  benchmark:
    strategy:
      matrix:
        target: [ 'net10.0', 'net6.0' ]

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          10.0.x
          6.0.x

    - name: Install libssl1.1 (for .NET 5)
      run: |
        sudo apt-get update
        sudo apt-get install -y libssl1.1 || sudo apt-get install -y libssl-dev

    - name: Embed resources
      run: |
        dotnet run --project ./embedded -f ${{ matrix.target }} -- --force --quiet

    - name: Run benchmark
      run: |
        dotnet run --project ./tests  -c Release -f ${{ matrix.target }} -- \
          --benchmark  ##--short-run

        echo "# 🚀 Benchmark Result (${{ matrix.target }})" >> $GITHUB_STEP_SUMMARY
        cat BenchmarkDotNet.Artifacts/results/*.md >> $GITHUB_STEP_SUMMARY
