name: tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  tests:

    strategy:
      matrix:
        configuration: [Debug, Release]

        # net5.0 for Unity compatibility tests
        framework: [net9.0, net5.0]

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          10.x.x
          5.x.x

    - name: Tests
      run: |
        # embed latest content to src/
        dotnet run --project ./embedded  -c ${{ matrix.configuration }}  -f net8.0 -- --force --quiet

        # run tests
        dotnet run --project ./sample  -c ${{ matrix.configuration }}  -f ${{ matrix.framework }}
        dotnet run --project ./sample  -c ${{ matrix.configuration }}  -f ${{ matrix.framework }}  -- --pretty-print
