name: build

on:
  push:
    branches: [ "main" ]
    paths-ignore: [ '.github/**', 'docs/**' ]
  pull_request:
    branches: [ "main" ]
    paths-ignore: [ '.github/**', 'docs/**' ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]
        pretty-print: ["", "--pretty-print"]

        # net6.0 for Unity compatibility tests
        framework: [net10.0, net6.0]

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          10.x.x
          6.x.x

    - name: Embed resources
      run: |
        dotnet run --project ./embedded  -f net10.0 -- --force --quiet

    - name: Test
      run: |
        dotnet run --project ./tests  -c ${{ matrix.configuration }}  -f ${{ matrix.framework }}  -- ${{ matrix.pretty-print }}
